language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-lf-project' ]; then cd .. && eval "mv $currentfolder generator-lf-project" && cd generator-lf-project; fi

